---
variables:
  VERSION: 0.3.$CI_PIPELINE_ID
  HOST: "stand"

stages:
  - pull
  - deploy

pull:
  stage: pull
  tags:
    - "$HOST"
  script:
    - echo "Pulling from origin repository" 
    - cd /home/$HOST/guider-api-mvp
    - pwd
    - git pull https://$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD@gtl.guider.pro/guider/backend/dotnet_mongodb/
    - git log --oneline -15
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_COMMIT_MESSAGE =~ /make a pipeline/'
      when: manual
    - when: never

deploy:
  stage: deploy
  tags:
    - "$HOST"
  script:
    - echo "Deployment API $VERSION"
    - sleep 10
    - cd /home/$HOST
    - docker compose down dotnet-mongo-api
    - TAG=$VERSION docker compose up -d --build dotnet-mongo-api
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" && $CI_COMMIT_MESSAGE =~ /make a pipeline/'
      when: manual
    - when: never
